name: Lumina
version: 1.0.6

author: Nolwen
description: Lumina brings light to your server, a toolkit of versatile features designed to refine, connect, and enhance your world
website: https://github.com/NolwenDEV/Lumina

main: be.nolwen.lumina.Main
api-version: 1.20

commands:
    lumina:
        description: Access Lumina's Settings
        usage: "/lumina <parameter>"
    register:
        description: Register your account on the serveur
        usage: "/register <password> <captcha>"
    login:
        description: Log-in on the server
        usage: "/login <password> <captcha>"
    home:
        description: Return to one of your saved spots
        usage: "/home <name>"
    homes:
        description: List the places you've marked along your journey
    sethome:
        description: Mark this place as a place you want to find again
        usage: "/sethome <name>"
    delhome:
        description: Remove one of your marked location
        usage: "/delhome <name>"
    backpack:
        description: Access your portable storage
        usage: "/backpack"
        aliases: bp
    filter:
        description: Choose which items you automatically ignore when picking up
        usage: "/filter"
    message:
        description: Whisper to another player's ears
        usage: "/message <name> <message>"
        aliases: [msg, m]
    reply:
        description: Reply to another player's whispers
        usage: "/reply <message>"
        aliases: r
    teleporthere:
        description: Invite a player to come to your position / accept their invite
        usage: "/teleporthere <player>"
        aliases: [tphere, tpahere]
    teleportto:
        description: Travel instantly to another player / accept their request
        usage: "/teleportto <player>"
        aliases: [tpto, tpa]
    back:
        description: Return to the last place you stood before moving on
        usage: "/back"
    craft:
        description: Open a crafting table from wherever you are
        usage: "/craft"
        aliases: workbench
    trash:
        description: Dispose of unwanted items instantly
        usage: "/trash"