#   ______     ______     __   __     ______   __     ______     __  __     ______     ______     ______   __     ______     __   __    
#  /\  ___\   /\  __ \   /\ "-.\ \   /\  ___\ /\ \   /\  ___\   /\ \/\ \   /\  == \   /\  __ \   /\__  _\ /\ \   /\  __ \   /\ "-.\ \   
#  \ \ \____  \ \ \/\ \  \ \ \-.  \  \ \  __\ \ \ \  \ \ \__ \  \ \ \_\ \  \ \  __<   \ \  __ \  \/_/\ \/ \ \ \  \ \ \/\ \  \ \ \-.  \  
#   \ \_____\  \ \_____\  \ \_\\"\_\  \ \_\    \ \_\  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\ \_\    \ \_\  \ \_\  \ \_____\  \ \_\\"\_\ 
#    \/_____/   \/_____/   \/_/ \/_/   \/_/     \/_/   \/_____/   \/_____/   \/_/ /_/   \/_/\/_/     \/_/   \/_/   \/_____/   \/_/ \/_/ 
#  

# -------------------------------------------------------------------------------------------------------------------------------------------- #

PREFIX: "&dLumina &8●"
VERSION: "1.0.6"

# -------------------------------------------------------------------------------------------------------------------------------------------- #

MODULE: 
    PREMIUM: true
    
    AUTHENTICATION: true
    WHITELIST: true
    
    CHAT: true
    CREEPER_GRIEFING: true
    CROP_REPLANTER: true
    
    COMMAND:
        PRIVATE_MESSAGE: true
        
        TELEPORTATION: true
        BACKPACK: true
        FILTER: true
        TRASH: true
        HOME: true
        CRAFT: true
        BACK: true
       
# -------------------------------------------------------------------------------------------------------------------------------------------- #
         
CHAT:
    FORMAT:
        PUBLIC: "{CHAT_PREFIX} &8● &7{PLAYER} &8» &f{MESSAGE}"
        PRIVATE:
            SENT: "&8[&7To &8: &5{PLAYER}&8] &7{MESSAGE}"
            RECEIVED: "&8[&7From &8: &5{PLAYER}&8] &d{MESSAGE}"
            
    PREFIXES:
        DEFAULT: "&7Player"
                
        PLAYER_NAME_1: "&cAdministrator"
        PLAYER_NAME_2: "&bBuilder"