#   ______     ______     __   __     ______   __     ______     __  __     ______     ______     ______   __     ______     __   __    
#  /\  ___\   /\  __ \   /\ "-.\ \   /\  ___\ /\ \   /\  ___\   /\ \/\ \   /\  == \   /\  __ \   /\__  _\ /\ \   /\  __ \   /\ "-.\ \   
#  \ \ \____  \ \ \/\ \  \ \ \-.  \  \ \  __\ \ \ \  \ \ \__ \  \ \ \_\ \  \ \  __<   \ \  __ \  \/_/\ \/ \ \ \  \ \ \/\ \  \ \ \-.  \  
#   \ \_____\  \ \_____\  \ \_\\"\_\  \ \_\    \ \_\  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\ \_\    \ \_\  \ \_\  \ \_____\  \ \_\\"\_\ 
#    \/_____/   \/_____/   \/_/ \/_/   \/_/     \/_/   \/_____/   \/_____/   \/_/ /_/   \/_/\/_/     \/_/   \/_/   \/_____/   \/_/ \/_/ 
#  

# -------------------------------------------------------------------------------------------------------------------------------------------- #

PREFIX: "&dLumina &8●"
VERSION: "1.0.0"

# -------------------------------------------------------------------------------------------------------------------------------------------- #

MODULE:
    PREMIUM: true
    DATABASE: false
    
    CHAT: true
    CREEPER_GRIEFING: true
    CROP_REPLANTER: true
    
    COMMAND:
        PRIVATE_MESSAGE: true
        
        BACKPACK: true
        FILTER: true
        TRASH: true
        HOME: true
        CRAFT: true
        BACK: true

# -------------------------------------------------------------------------------------------------------------------------------------------- #

CHAT:
    FORMAT: "{CHAT_PREFIX} &8● &7{PLAYER} &8» &f{MESSAGE}"
    PREFIXES:
        DEFAULT: "&7Player"
        
        PLAYER_NAME_1: "&cAdministrator"
        PLAYER_NAME_2: "&bBuilder"