#   _____     ______     ______   ______     ______     ______     ______     ______    
#  /\  __-.  /\  __ \   /\__  _\ /\  __ \   /\  == \   /\  __ \   /\  ___\   /\  ___\   
#  \ \ \/\ \ \ \  __ \  \/_/\ \/ \ \  __ \  \ \  __<   \ \  __ \  \ \___  \  \ \  __\   
#   \ \____-  \ \_\ \_\    \ \_\  \ \_\ \_\  \ \_____\  \ \_\ \_\  \/\_____\  \ \_____\ 
#    \/____/   \/_/\/_/     \/_/   \/_/\/_/   \/_____/   \/_/\/_/   \/_____/   \/_____/ 
#                                                                                       

# -------------------------------------------------------------------------------------------------------------------------------------------- #

ENABLED: false

HOSTNAME: "127.0.0.1:3306"
USERNAME: "User"
PASSWORD: "Password"
NAME: "Lumina"